# Generated by Django 5.0.1 on 2024-01-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="series_id", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(db_column="title", max_length=200)),
                ("release_date", models.DateField(db_column="release_date")),
                ("creator", models.CharField(db_column="creator", max_length=100)),
                ("description", models.TextField(db_column="description")),
            ],
            options={
                "db_table": "Series",
            },
        ),
    ]
