# Generated by Django 4.0.4 on 2023-09-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(db_column='series_id', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('creator', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
