# Generated by Django 4.0.4 on 2023-09-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='id',
            field=models.AutoField(db_column='movies_id', primary_key=True, serialize=False),
        ),
    ]
