APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.movies',
    'apps.series',
    'apps.users',
    'drf_yasg',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
]