# Generated by Django 4.0.4 on 2023-11-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(db_column='movies_id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=200)),
                ('release_date', models.DateField(db_column='release_date')),
                ('director', models.CharField(db_column='director', max_length=100)),
                ('description', models.TextField(db_column='description')),
                ('rating', models.DecimalField(blank=True, db_column='rating', decimal_places=1, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'Movies',
            },
        ),
    ]
