# Generated by Django 4.0.4 on 2024-01-08 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='rol',
            field=models.ForeignKey(db_column='rol_user', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='roles.roles'),
        ),
    ]
