# Generated by Django 4.0.4 on 2023-11-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_person_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='person',
            name='nombre',
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, db_column='last_name', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, db_column='name', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(db_column='users_id', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='person',
            table='Users',
        ),
    ]
